
output:
  beamer_presentation:
    theme: "Hannover"
    colortheme: "dove"
    fonttheme: "professionalfonts"
    #citation_package: natbib
    includes:
      in_header: Infrastructure/matrix.tex
    #pandoc_args: [ "--filter", "pandoc-citeproc" ]
    latex_engine: xelatex
    slide_level: 3
  powerpoint_presentation:
    reference_doc: Infrastructure/LSHTM_Presentation_Template_4.3a.pptx
    #pandoc_args: ["--filter", "pandoc-citeproc"]
    slide_level: 3
tables: yes
header-includes:
  -\usepackage{hyperref}
  -\usepackage{amsmath}
  -\renewcommand{\vec}[1]{\mathbf{#1}}
  -\newcommand{\derivn}[3]{\frac{\textrm{d}^{#3}#1}{\textrm{d}#2 ^{#3}}}
  -\newcommand{\deriv}[2]{\frac{\textrm{d}#1}{\textrm{d}#2}}
  -\newcommand{\dx}[1]{\,\textrm{d}#1}
  -\newcommand{\Derivn}[3]{\frac{\Delta^{#3}#1}{\Delta#2 ^{#3}}}
  -\newcommand{\Deriv}[2]{\frac{\Delta#1}{\Delta#2}}
  -\newcommand{\Dx}[1]{\,\Delta#1}
  -\usepackage{booktabs}
bibliography: Infrastructure/extras.bib
csl: Infrastructure/science_without_titles.csl
